services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: loja-db
    environment:
      - 'POSTGRES_DB=relojoaria'
      - 'POSTGRES_PASSWORD=loja'
      - 'POSTGRES_USER=loja'
    ports:
      - '5432:5432'
